### ISSUE TITLE
Support win32.

### ISSUE THREAD

**Issue by lygstate** [NuxiNL/cloudlibc#2]
That's would be great if cloundlibc would support for win32.

**Comment by EdSchouten** [comment]
Hi Yonggang,

It's important to keep in mind that CloudABI is its own separate runtime environment. There is no need to make any adjustments to cloudlibc to make CloudABI applications run on other systems. The operating themselves need to be adjusted to support CloudABI. The reason for this is that the kernel is required to enforce CloudABI's capability-based security policy.

In other words, we would need to modify the NT kernel to support CloudABI programs. I cannot reasonably see this happen within the nearby future. The NT kernel is not open source, meaning that there is no way we can implement this.

Closing this, as there is nothing actionable.
