### ISSUE TITLE
Debian runtime packages appear to be empty?

### ISSUE THREAD

**Issue by mcandre** [NuxiNL/cloudlibc#25]
```console
$ dpkg --listfiles x86-64-unknown-cloudabi-c-runtime
/.
$ dpkg --listfiles x86-64-unknown-cloudabi-cxx-runtime
/.
```

Am I doing this right?

**Comment by m-ou-se** [comment]
Yes, they are empty, but have dependencies:

https://github.com/NuxiNL/cloudabi-ports/blob/246cf495c4f419eb06c771153ce4473da97d1ac1/packages/cxx-runtime/BUILD#L9
