### ISSUE TITLE
Query program name programmatically

### ISSUE THREAD

**Issue by mcandre** [NuxiNL/cloudlibc#27]
Lacking the traditional `int argc, char **argv` entrypoint parameters for querying command line arguments, could program.h provide another way to obtain the name of the program? This is often useful for displaying accurate help command syntax for downstream users.

**Comment by EdSchouten** [comment]
I think the answer to this question is somewhat similar to my response to https://github.com/NuxiNL/cloudabi-utils/issues/11. Something like this could be built on top of what's there already. The argdata could be used to communicate this information to the process.

Let's close this issue to keep the discussion centralized.
